[package]
name = "space-invaders"
version = "0.1.0"
authors = ["Dzenan Jupic <56133904+DzenanJupic@users.noreply.github.com>"]
edition = "2018"

[dependencies]
array-init = "1.0.0"
log = "0.4.13"
rand = "0.8.1"
getrandom = { version = "0.2.1", features = ["wasm-bindgen", "js"] }
